modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="chaosenchants"
version="1.0.0"
displayName="Chaos Enchants"
authors="Arkonix / Ob3yPlays"
description='''
Every item that enters your inventory receives completely random enchantments with random levels.
No item rules. No compatibility rules. Impossible combinations allowed.
'''

[[dependencies.chaosenchants]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaosenchants]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
